services:
  app:
    # Run the image pre-built from github
    # This should be marked as public within the github packages configuration
    # or credentials provided to access
    image: ghcr.io/supportingami/trinket-oss:latest
    ports:
      - 3000:3000
    container_name: trinket
    volumes:
      - node_modules:/usr/local/node/trinket/node_modules
      - public_components:/usr/local/node/trinket/public/components
    networks:
      - trinket
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - trinket

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - trinket

networks:
  trinket:
    driver: bridge

volumes:
  node_modules:
  public_components:
  mongodb_data:
