services:
  app:
    build: .
    image: trinket/app:latest
    ports:
      - 3000:3000
    container_name: trinket
    volumes:
      - .:/usr/local/node/trinket
      - node_modules:/usr/local/node/trinket/node_modules
      - public_components:/usr/local/node/trinket/public/components
    networks:
      - trinket
    links:
      - redis
      - mongodb
    command: bash -c "npm run build:css && pm2-docker start app.js"
  redis:
    image: redis:alpine
    ports:
      - 16379:6379
    container_name: redis
    networks:
      - trinket
  mongodb:
    image: mongo:7.0
    ports:
      - 17017:27017
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - trinket
networks:
  trinket:
    driver: bridge
volumes:
  shared-cache:
  node_modules:
  public_components:
  mongodb_data:
